version: '3.8'

services:
  invoices-api:
    build: ./
    command:  ./invoices-api
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - invoices-db
    environment:
      - "DB_HOST=invoices-db"
      - "DB_PORT=5432"
      - "DB_USERNAME=postgres"
      - "DB_PASSWORD=qwerty"
      - "DB_NAME=postgres"
      - "SSL_MODE=disable"

  invoices-db:
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_PASSWORD=qwerty"